# Generated by Django 6.0.5 on 2026-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_powersupply_ram_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='tdp',
            field=models.IntegerField(default=150, help_text='Тепловыделение в Вт'),
        ),
    ]
