# Generated by Django 6.0.5 on 2026-05-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_gpu_tdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('name', models.CharField(default='Моя сборка', max_length=100, verbose_name='Название сборки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builder.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builder.gpu')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builder.motherboard')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builder.powersupply')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builder.ram')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builder.storage')),
            ],
        ),
    ]
